name: "laravel-practical-2026"

services:
    cli:
        volumes:
            - '.:/var/www/html'
        build:
            context: .
            dockerfile: docker/php/cli.DockerFile
        depends_on:
            - mysql
            - redis
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
            DB_USERNAME: laravel
            DB_PASSWORD: secret

    background:
        volumes:
            - '.:/var/www/html'
        build:
            context: .
            dockerfile: docker/php/background.DockerFile
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
            DB_USERNAME: laravel
            DB_PASSWORD: secret

    web:
        volumes:
            - '.:/var/www/html'
        build:
            context: .
            dockerfile: docker/php/nginx.DockerFile
        ports:
            - "8888:8080"
            - "9009:9001"
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
            DB_USERNAME: laravel
            DB_PASSWORD: secret

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: society
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3308:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootsecret"]
            interval: 5s
            timeout: 5s
            retries: 10

    redis:
        image: redis:8.2
        healthcheck:
            test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
            interval: 1s
            timeout: 3s
            retries: 5
        ports:
            - "6379:6379"
        command: [ "redis-server" ]
        volumes:
            - redis-data:/data

volumes:
    mysql-data:
    redis-data:
