#!/command/with-contenv sh
# Queue Default-2 Service
# Runs Laravel queue worker #2 for default queue

set -e

echo "[queue-default-2] Starting Laravel Queue Worker #2 for default queue..."

cd /var/www/html

exec php artisan queue:work \
    --queue=notification,email,default \
    --sleep=3 \
    --tries=3 \
    --max-time=3600 \
    --verbose

