#!/command/with-contenv sh
# Cron Finish Script
# Graceful shutdown handler for cron

echo "[cron] Cron stopped with exit code: $1"

if [ "$1" -ne 0 ]; then
    echo "[cron] Cron exited with error, container will restart"
fi

exit 0

