#!/command/with-contenv sh
# Queue Default-1 Finish Script
# Graceful shutdown handler for default queue worker #1

echo "[queue-default-1] Default queue worker #1 stopped with exit code: $1"

if [ "$1" -ne 0 ]; then
    echo "[queue-default-1] Worker exited with error, container will restart"
fi

exit 0

